name: make lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pwd
      run: pwd
    - name: install deps
      run: npm install
    - name: run lint
      run: make lint
      uses: actions/setup-node@v1
    - run: make lint
    - run: npm run build --if-present
      env:
        CI: true