name: make lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
    - name: install deps
      run: npm install
    - name: npm run build
      run: npm run build
    - name: run lint
      run: make lint
      with:
        node-version: '12'
      run: make install
    - run: make lint
    - run: npm run build
      env:
        CI: true