name: make lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pwd
      run: pwd
    - name: install deps
      run: npm install
    - name: run lint
      run: make lint
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
       with:
        node-version: '12'
      run: make install
    - run: make lint
    - run: npm run build
      env:
        CI: true